#!/usr/bin/env python3
"""
=============================================================================
 2.5D Multi-Layer Path Planner
 File: planners/planner_3d.py
=============================================================================

 Altitude-aware path planning using a multi-layer approach.

 Instead of full 3D grid search (1.2M voxels = too slow for real-time),
 this planner uses 3 discrete altitude layers:

   Layer 0: z = 1.2m  (low — under most hanging obstacles)
   Layer 1: z = 1.8m  (default flight altitude)
   Layer 2: z = 2.4m  (high — above most furniture, below ceiling)

 For each layer, a 2D occupancy grid is generated by querying the 3D
 OctoMap at that layer's altitude range. The planner then runs A* on a
 layered graph where nodes are (row, col, layer) and edges connect:
   - 8 horizontal neighbors on the same layer (standard 2D movement)
   - Same (row, col) on adjacent layers (altitude transitions)

 Altitude changes carry an extra cost penalty to model the real-world
 battery cost of climbing/descending. The drone only changes altitude
 when it MUST (e.g., pipe blocking the default layer).

 Output: list of (x, y, z) waypoints with variable altitude.

=============================================================================
"""

import math
import heapq
import numpy as np

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from core.octomap_3d_query import OctoMap3DQuery


# ─────────────────────────────────────────────────────────────────────────────
#  ALTITUDE LAYERS
# ─────────────────────────────────────────────────────────────────────────────
# Each layer defines: (altitude, clearance_below, clearance_above)
# The drone checks that the vertical column at each cell is free
# from (altitude - clearance_below) to (altitude + clearance_above).

Z_LAYERS = [1.2, 1.8, 2.4]       # metres — low, default, high
DRONE_CLEARANCE = 0.3             # metres above and below drone center
DEFAULT_LAYER = 1                 # index into Z_LAYERS (1.8m)

# Cost multipliers
ALTITUDE_CHANGE_COST = 5.0        # Extra cost per layer transition
                                  # (penalizes unnecessary altitude changes)
DIAGONAL_COST = 1.414             # sqrt(2) for diagonal grid moves


class MultiLayerPlanner:
    """
    2.5D A* planner with Theta*-style line-of-sight shortcuts.

    Uses:
      - A 2D OccupancyGrid (from /projected_map) for grid structure
      - An OctoMap3DQuery instance for 3D collision checks per layer
    """

    def __init__(self, occupancy_grid_msg, octomap_3d, safety_margin=0.25, unknown_penalty=3.0):
        """
        Args:
            occupancy_grid_msg: nav_msgs/OccupancyGrid from /projected_map
            octomap_3d: OctoMap3DQuery instance with loaded 3D data
            safety_margin: Obstacle inflation radius (metres)
            unknown_penalty: Cost added per unmapped cell
        """
        info = occupancy_grid_msg.info
        self.unknown_penalty = unknown_penalty
        self.resolution = info.resolution
        self.origin_x = info.origin.position.x
        self.origin_y = info.origin.position.y
        self.width = info.width
        self.height = info.height
        self.octomap_3d = octomap_3d

        # Base 2D grid from projected map (for grid structure/bounds)
        raw = np.array(occupancy_grid_msg.data).reshape((self.height, self.width))
        self.raw = raw  # Save raw grid to check for -1 (unknown) cells
        base_grid = np.where(raw > 50, 1, 0).astype(np.uint8)

        # Build per-layer occupancy grids
        self.num_layers = len(Z_LAYERS)
        self.layer_grids = []

        for layer_idx, z_alt in enumerate(Z_LAYERS):
            layer_grid = self._build_layer_grid(base_grid, z_alt)
            layer_grid = self._inflate(layer_grid, safety_margin)
            self.layer_grids.append(layer_grid)

        # Print layer summary
        for i, z in enumerate(Z_LAYERS):
            occupied = int(np.sum(self.layer_grids[i]))
            total = self.width * self.height
            print(f"    Layer {i} (z={z:.1f}m): "
                  f"{occupied}/{total} blocked cells "
                  f"({100*occupied/total:.1f}%)")

    def _build_layer_grid(self, base_grid, z_alt):
        """
        Build a 2D occupancy grid for a specific altitude layer.

        A cell is occupied if:
          1. It's occupied in the base 2D projected map, OR
          2. The 3D OctoMap has obstacles in the vertical column at
             that cell's (x,y) within [z_alt - clearance, z_alt + clearance]
        """
        grid = np.copy(base_grid)

        if not self.octomap_3d.is_ready:
            return grid

        z_min = z_alt - DRONE_CLEARANCE
        z_max = z_alt + DRONE_CLEARANCE

        # Check each cell for 3D obstacles at this altitude
        # Optimization: only check cells that are currently FREE in 2D
        # (already-blocked cells stay blocked)
        free_cells = np.argwhere(grid == 0)

        for r, c in free_cells:
            x, y = self._grid_to_world(r, c)
            if not self.octomap_3d.is_column_clear(x, y, z_min, z_max,
                                                    xy_radius=0.2):
                grid[r, c] = 1  # Mark as occupied at this altitude

        return grid

    def _inflate(self, grid, margin_m):
        """Grow obstacle cells by margin_m metres in all directions."""
        cells = int(math.ceil(margin_m / self.resolution))
        if cells <= 0:
            return grid

        inflated = np.copy(grid)
        obstacles = np.argwhere(grid == 1)

        for r, c in obstacles:
            r_lo = max(0, r - cells)
            r_hi = min(self.height, r + cells + 1)
            c_lo = max(0, c - cells)
            c_hi = min(self.width, c + cells + 1)
            inflated[r_lo:r_hi, c_lo:c_hi] = 1

        return inflated

    # ── Coordinate Helpers ────────────────────────────────────────────────

    def world_to_grid(self, x, y):
        """World (x, y) → grid (row, col)."""
        c = int((x - self.origin_x) / self.resolution)
        r = int((y - self.origin_y) / self.resolution)
        return r, c

    def _grid_to_world(self, r, c):
        """Grid (row, col) → world (x, y)."""
        x = self.origin_x + (c + 0.5) * self.resolution
        y = self.origin_y + (r + 0.5) * self.resolution
        return x, y

    def is_free(self, r, c, layer):
        """Check if (r, c) is free on the given layer."""
        return (0 <= r < self.height and
                0 <= c < self.width and
                self.layer_grids[layer][r, c] == 0)

    # ── 2.5D A* Search ───────────────────────────────────────────────────

    def plan(self, sx, sy, gx, gy, start_layer=None, goal_layer=None):
        """
        Plan a 2.5D path from (sx, sy) to (gx, gy).

        The planner searches across all altitude layers and finds the
        optimal path that may include altitude transitions.

        Args:
            sx, sy: Start world coordinates (metres).
            gx, gy: Goal world coordinates (metres).
            start_layer: Starting layer index (default: DEFAULT_LAYER).
            goal_layer: Goal layer index (default: any layer).

        Returns:
            List of (x, y, z) waypoints, or None if no path found.
        """
        if start_layer is None:
            start_layer = DEFAULT_LAYER

        start_rc = self.world_to_grid(sx, sy)
        goal_rc = self.world_to_grid(gx, gy)

        # Clamp to grid bounds
        start_rc = (
            max(0, min(self.height - 1, start_rc[0])),
            max(0, min(self.width - 1, start_rc[1]))
        )
        goal_rc = (
            max(0, min(self.height - 1, goal_rc[0])),
            max(0, min(self.width - 1, goal_rc[1]))
        )

        # If start is in obstacle on the given layer, find nearest free cell
        if not self.is_free(start_rc[0], start_rc[1], start_layer):
            start_rc, start_layer = self._nearest_free_3d(start_rc, start_layer)
            if start_rc is None:
                print("  ❌ Cannot find free start cell on any layer!")
                return None

        # Start node: (row, col, layer)
        start = (start_rc[0], start_rc[1], start_layer)

        # If goal_layer is None, accept goal at any layer
        # For A*, we'll check goal matching in the loop

        # A* with layered graph
        open_set = []
        heapq.heappush(open_set, (0.0, start))
        came_from = {start: None}
        g = {start: 0.0}

        # 8-connected horizontal moves
        h_dirs = [(0, 1), (1, 0), (0, -1), (-1, 0),
                  (1, 1), (1, -1), (-1, 1), (-1, -1)]

        goal_found = None

        while open_set:
            _, cur = heapq.heappop(open_set)
            cr, cc, cl = cur

            # Goal check: same (r, c), and either any layer or specific layer
            if (cr, cc) == goal_rc:
                if goal_layer is None or cl == goal_layer:
                    goal_found = cur
                    break

            # ── Horizontal neighbors (same layer) ──
            for dr, dc in h_dirs:
                nr, nc = cr + dr, cc + dc
                if not self.is_free(nr, nc, cl):
                    continue

                penalty = self.unknown_penalty if self.raw[nr, nc] == -1 else 0.0
                step = (DIAGONAL_COST if (dr and dc) else 1.0) + penalty
                ng = g[cur] + step
                nxt = (nr, nc, cl)

                if nxt not in g or ng < g[nxt]:
                    g[nxt] = ng
                    # Heuristic: Euclidean distance to goal (2D) + layer penalty
                    h = math.hypot(goal_rc[0] - nr, goal_rc[1] - nc)
                    if goal_layer is not None:
                        h += ALTITUDE_CHANGE_COST * abs(cl - goal_layer)
                    heapq.heappush(open_set, (ng + h, nxt))
                    came_from[nxt] = cur

            # ── Vertical neighbors (altitude transitions) ──
            # The drone can change altitude at its current (r, c)
            for dl in [-1, +1]:
                nl = cl + dl
                if nl < 0 or nl >= self.num_layers:
                    continue
                if not self.is_free(cr, cc, nl):
                    continue

                # Altitude change cost: base transition + height difference
                dz = abs(Z_LAYERS[nl] - Z_LAYERS[cl])
                ng = g[cur] + ALTITUDE_CHANGE_COST * (dz / 0.6)
                nxt = (cr, cc, nl)

                if nxt not in g or ng < g[nxt]:
                    g[nxt] = ng
                    h = math.hypot(goal_rc[0] - cr, goal_rc[1] - cc)
                    if goal_layer is not None:
                        h += ALTITUDE_CHANGE_COST * abs(nl - goal_layer)
                    heapq.heappush(open_set, (ng + h, nxt))
                    came_from[nxt] = cur

        if goal_found is None:
            print("  ❌ No 2.5D path found!")
            return None

        # Reconstruct path
        path_3d = []
        cur = goal_found
        while cur is not None:
            r, c, layer = cur
            x, y = self._grid_to_world(r, c)
            z = Z_LAYERS[layer]
            path_3d.append((x, y, z))
            cur = came_from[cur]
        path_3d.reverse()

        # Return the dense path for proper pure pursuit tracking and collision checking
        return path_3d

    # ── 2.5D Theta* (any-angle with altitude) ─────────────────────────────

    def plan_theta_star(self, sx, sy, gx, gy, start_layer=None, goal_layer=None):
        """
        Plan a 2.5D path using Theta* (any-angle line-of-sight shortcuts).

        Same as plan() but adds line-of-sight checks: when expanding a node,
        if there's a clear line from the grandparent to the current node on
        the same layer, skip the parent for a straighter path.

        Args:
            sx, sy: Start world coordinates.
            gx, gy: Goal world coordinates.
            start_layer: Starting layer index.
            goal_layer: Goal layer index (None = any).

        Returns:
            List of (x, y, z) waypoints, or None if no path found.
        """
        if start_layer is None:
            start_layer = DEFAULT_LAYER

        start_rc = self.world_to_grid(sx, sy)
        goal_rc = self.world_to_grid(gx, gy)

        start_rc = (
            max(0, min(self.height - 1, start_rc[0])),
            max(0, min(self.width - 1, start_rc[1]))
        )
        goal_rc = (
            max(0, min(self.height - 1, goal_rc[0])),
            max(0, min(self.width - 1, goal_rc[1]))
        )

        if not self.is_free(start_rc[0], start_rc[1], start_layer):
            start_rc, start_layer = self._nearest_free_3d(start_rc, start_layer)
            if start_rc is None:
                print("  ❌ Cannot find free start cell on any layer!")
                return None

        start = (start_rc[0], start_rc[1], start_layer)

        open_set = []
        heapq.heappush(open_set, (0.0, start))
        came_from = {start: None}
        g = {start: 0.0}

        h_dirs = [(0, 1), (1, 0), (0, -1), (-1, 0),
                  (1, 1), (1, -1), (-1, 1), (-1, -1)]

        goal_found = None

        while open_set:
            _, cur = heapq.heappop(open_set)
            cr, cc, cl = cur

            if (cr, cc) == goal_rc:
                if goal_layer is None or cl == goal_layer:
                    goal_found = cur
                    break

            # ── Horizontal neighbors with Theta* shortcut ──
            for dr, dc in h_dirs:
                nr, nc = cr + dr, cc + dc
                if not self.is_free(nr, nc, cl):
                    continue

                nxt = (nr, nc, cl)

                # Theta* check: can we shortcut from grandparent?
                parent = came_from.get(cur)
                if (parent is not None and parent[2] == cl
                        and self._line_of_sight(parent[0], parent[1],
                                                nr, nc, cl)):
                    # Direct line from grandparent to neighbor
                    pr, pc, _ = parent
                    new_g = g[(pr, pc, cl)] + math.hypot(nr - pr, nc - pc)
                    use_parent = parent
                else:
                    # Standard A* path through cur
                    step = DIAGONAL_COST if (dr and dc) else 1.0
                    new_g = g[cur] + step
                    use_parent = cur

                if nxt not in g or new_g < g[nxt]:
                    g[nxt] = new_g
                    h = math.hypot(goal_rc[0] - nr, goal_rc[1] - nc)
                    if goal_layer is not None:
                        h += ALTITUDE_CHANGE_COST * abs(cl - goal_layer)
                    heapq.heappush(open_set, (new_g + h, nxt))
                    came_from[nxt] = use_parent

            # ── Vertical neighbors (same as A*) ──
            for dl in [-1, +1]:
                nl = cl + dl
                if nl < 0 or nl >= self.num_layers:
                    continue
                if not self.is_free(cr, cc, nl):
                    continue

                dz = abs(Z_LAYERS[nl] - Z_LAYERS[cl])
                ng = g[cur] + ALTITUDE_CHANGE_COST * (dz / 0.6)
                nxt = (cr, cc, nl)

                if nxt not in g or ng < g[nxt]:
                    g[nxt] = ng
                    h = math.hypot(goal_rc[0] - cr, goal_rc[1] - cc)
                    if goal_layer is not None:
                        h += ALTITUDE_CHANGE_COST * abs(nl - goal_layer)
                    heapq.heappush(open_set, (ng + h, nxt))
                    came_from[nxt] = cur

        if goal_found is None:
            print("  ❌ No 2.5D Theta* path found!")
            return None

        path_3d = []
        cur = goal_found
        while cur is not None:
            r, c, layer = cur
            x, y = self._grid_to_world(r, c)
            z = Z_LAYERS[layer]
            path_3d.append((x, y, z))
            cur = came_from[cur]
        path_3d.reverse()

        # Return the dense path for proper pure pursuit tracking and collision checking
        return path_3d

    # ── Line-of-Sight Check (Bresenham) ───────────────────────────────────

    def _line_of_sight(self, r0, c0, r1, c1, layer):
        """
        Bresenham line-of-sight check between (r0,c0) and (r1,c1)
        on a specific layer. Returns True if all cells on the line
        are free.
        """
        dr = abs(r1 - r0)
        dc = abs(c1 - c0)
        sr = 1 if r1 > r0 else -1
        sc = 1 if c1 > c0 else -1

        r, c = r0, c0

        if dc > dr:
            err = dc // 2
            while c != c1:
                if not self.is_free(r, c, layer):
                    return False
                err -= dr
                if err < 0:
                    r += sr
                    err += dc
                c += sc
        else:
            err = dr // 2
            while r != r1:
                if not self.is_free(r, c, layer):
                    return False
                err -= dc
                if err < 0:
                    c += sc
                    err += dr
                r += sr

        return self.is_free(r1, c1, layer)

    # ── Helpers ───────────────────────────────────────────────────────────

    def _nearest_free_3d(self, cell, preferred_layer):
        """
        BFS outward to find the nearest free cell, checking all layers.
        Returns ((r, c), layer) or (None, None).
        """
        # First try preferred layer
        result = self._nearest_free_2d(cell, preferred_layer)
        if result is not None:
            return result, preferred_layer

        # Try other layers
        for layer in range(self.num_layers):
            if layer == preferred_layer:
                continue
            result = self._nearest_free_2d(cell, layer)
            if result is not None:
                return result, layer

        return None, None

    def _nearest_free_2d(self, cell, layer):
        """BFS outward on a single layer to find nearest free cell."""
        if self.is_free(cell[0], cell[1], layer):
            return cell

        visited = {cell}
        queue = [cell]
        while queue:
            next_queue = []
            for r, c in queue:
                for dr in range(-1, 2):
                    for dc in range(-1, 2):
                        nb = (r + dr, c + dc)
                        if nb not in visited:
                            if self.is_free(nb[0], nb[1], layer):
                                return nb
                            visited.add(nb)
                            next_queue.append(nb)
            queue = next_queue
        return None

    def _simplify_3d(self, path):
        """
        Remove collinear intermediate waypoints from a 3D path.
        Keeps altitude-change waypoints (where z differs).
        """
        if len(path) < 3:
            return path

        result = [path[0]]
        for i in range(1, len(path) - 1):
            x0, y0, z0 = path[i - 1]
            x1, y1, z1 = path[i]
            x2, y2, z2 = path[i + 1]

            # Always keep altitude transition points
            if z0 != z1 or z1 != z2:
                result.append(path[i])
                continue

            # Check collinearity in XY (same as 2D simplify)
            dx1, dy1 = x1 - x0, y1 - y0
            dx2, dy2 = x2 - x1, y2 - y1
            cross = abs(dx1 * dy2 - dx2 * dy1)
            if cross > 1e-4:
                result.append(path[i])

        result.append(path[-1])
        return result


# ─────────────────────────────────────────────────────────────────────────────
#  Standalone test
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    print("MultiLayerPlanner module loaded successfully.")
    print(f"  Altitude layers: {Z_LAYERS}")
    print(f"  Drone clearance: ±{DRONE_CLEARANCE}m")
    print(f"  Altitude change cost: {ALTITUDE_CHANGE_COST}")
    print(f"  Default layer: {DEFAULT_LAYER} (z={Z_LAYERS[DEFAULT_LAYER]}m)")
